name: Hello World
on:
  push:
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4
      - name: Echo text
        run: echo "Hello, world!!
