name: Generate ASCII Artwork 
on:
  workflow_dispatch:
jobs:
  build-artwork: 
    runs-on: ubuntu-latest
    steps:
    - run: |-
          curl -s https://api.adviceslip.com/advice > advice.json
          cat advice.json
          
          cat advice.json | jq -r .slip.advice > advice.message
          [ $(wc -w < advice.message) -gt 5 ] && echo "Advice has more than 5 words" || (echo "Advice - $(cat advice.message)  has 5 words or less" && exit 1)
          
          sudo apt-get install cowsay -y
          echo $PATH
          export PATH="$PATH:/usr/games:/usr/local/games"
          cat advice.message | cowsay -f $(ls /usr/share/cowsay/cows | shuf -n 1)

